### ISSUE TITLE
Kintone から WP へ post する plug-in wp-kintone を使ったテスト サイトの構築と確認

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#1]
**kintoneアクセスURL：**
https://xxxx.cybozu.com
* kintoneの開発者アカウント
ログイン名： xxxx
パスワード： xxxx
* スタッフ
ログイン名： xxxx
パスワード： xxxx
* チーフ
ログイン名： xxxx
パスワード： xxxx
**WordPress側adminログイン：**
https://neo-xxxx.sakura.ne.jp/xxxx/wp-admin
ログイン名： xxxx
パスワード： xxxx

**使用手順**
> kintoneアクセスURL：
> https://xxxx.cybozu.com

**日記投稿**
> スタッフでログインします。
> Kintone-WordPress-日記　アプリを開きます
> 右上の追加ボタンでレコードを追加します
> 保存したら、左上の「提出」で「管理者」を選び実行します

**承認フロー実施**
> 管理者でログインします。
> 未処理にKintone-WordPress-日記の通知が来ているので開きます
> 左上の「承認完了とする」で「承認済み・WEB反映」を選び実行します。(差し戻して繰り返してもよいです)

> WordPress側adminログインします
> https://neo-xxxx.sakura.ne.jp/xxxx/wp-admin
> ログイン名： xxxx
> パスワード： xxxx
> 左側の「投稿一覧」をみると、投稿した日記が「下書き」で反映されています。
> 該当の日記のタイトルをマウスで示すと、メニューに「編集」が表示されるのでクリックします。
> そのまま、右上の「公開」をクリック、そのまま公開します。
> 右側に「投稿を表示」をクリックします。
> 内容を確認します。

一連の流れでした。

**現在の問題点**
kintoneの承認フローに、チーフを入れました。が、管理者でないとWP側に投稿されません。(何らかのアクセス権限が制限されている模様)
WP側に送ると、WP側プラグインのデフォルトでは「下書き」になります。(カスタマイズで解消できます)
WP側を公開・更新すると、添付した画像ファイルがどんどん増殖します。
以上、確認をお願いします。

**Comment by genepine** [comment]
#11 で確認する

**Comment by Gucchiy** [comment]
11/18 付け打ち合わせにてクローズ承認
