### ISSUE TITLE
ユーザにアプリ管理権限を割り当てた時の動作確認

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#11]
ユーザを作成すると規定ではアプリ管理権限が割り当てられていない
その状態だと管理者でないとKintoneからWordPressに記事を送れないことが判明。
新たにアプリ管理権限をeveryoneに設定したため、動作を確認する。
管理者
チーフ
スタッフ
help
https://faq.cybozu.info/alphascope/cybozu/web/kintone/Detail.aspx?id=1857&isCrawler=1

**Comment by genepine** [comment]
スタッフで投稿し
チーフで承認できた
この件については終了
しかし #12  ユーザー staffで「保存のみ」で記事がWordPress側に送られることが判明

**Comment by Gucchiy** [comment]
Close 処理は neo 様のご確認を取ったうえで行わせてくださいませ！

**Comment by genepine** [comment]
#12 と兼ね合いを検討する

**Comment by genepine** [comment]
動作確認は未実施
ユーザ　アプリ管理権限　既定
![Image_20201117_140613](https://user-images.githubusercontent.com/40847696/99349571-acfcd180-28df-11eb-82eb-56fbff41cbc0.png)

ユーザ　アプリ管理権限　割り当て例　管理者　チーフ　作成者のみ
![Image_20201117_140831](https://user-images.githubusercontent.com/40847696/99349588-b38b4900-28df-11eb-896d-98fd1f21c510.png)

**Comment by myama2** [comment]
ネオのポリシーで、「Everyoneは全てチェックを外す。スタッフはアプリ管理を外す。」としたいのですが可能でしょうか。

**Comment by genepine** [comment]
設定しました(neoのアカウントではありません)
![Image_20201117_140831](https://user-images.githubusercontent.com/40847696/99355251-47aedd80-28eb-11eb-91c3-1a49f2722875.png)

**Comment by Gucchiy** [comment]
Kintone 側の権限設定は、WP 側プラグインでは加味されていないのではないかと想像されます。一旦、neo 様側の権限は自由に設定して頂いて問題ないということをご回答として、本件は緊急度を下げます。

**Comment by Gucchiy** [comment]
承認フローが実装されたため、クローズ
