### ISSUE TITLE
画像添付が1回目の保存時には反映されず、2回目に反映される

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#13]
本件は不具合かと思いますので、作者様にご連絡いたします。

**Comment by Gucchiy** [comment]
取り急ぎ、作者様にバグ報告してみました。ここでいいのかな・・
https://wordpress.org/support/topic/%e7%94%bb%e5%83%8f%e6%b7%bb%e4%bb%98%e3%81%8c%e4%bf%9d%e5%ad%98%e6%99%82%e3%81%ab%e3%81%af%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84/#new-topic-0

**Comment by Gucchiy** [comment]
先方からバグ詳細確認のご連絡あり。スクリーンショットを提出。

**Comment by Gucchiy** [comment]
以下、うっかり Slack でやりとりしてしまいましたので、こちらにログを残します！

Gucchiy  1日前
@genepine 返信来ましたー。以下って松野さん、対応可能でしょうか？ご検討、どうぞよろしくお願いいたします！
single.php の表示させたい箇所に以下のコードを記載すると良いかなーと思いました。
管理画面から保存したら表示される現象は管理画面から保存されることで Advanced Custom Fields としてデータが保存がされるからだと思います。
Advanced Custom Fields を経由せずにカスタムフィールドを使用して表示させると良いと思います！
https://gist.github.com/tkc49/af32ce37f2db571e6ebb5f43c2f19ba2

genepine  1日前
↑のコードに書き換え
neo-kintone.sakura.ne.jp
katawara-child\template-parts\post\content.php
kintoneから1回で画像表示できました
ただし　承認フローで「提出」しないと 2枚目の画像が表示されません。タグも同じく。メディアライブラリに画像は飛んでます
いったん承認フローを外して基本動作を完成させたほうが良いですね

**Comment by genepine** [comment]
> ただし　承認フローで「提出」しないと 2枚目の画像が表示されません。タグも同じく。メディアライブラリに画像は飛んでます
> いったん承認フローを外して基本動作を完成させたほうが良いですね
上の件
WordPressフォーラムでPublish Kintone Dataの作者に質問した件の改修により、解消しました。
[KintoneアプリRich Text formの文字色・背景色がタグのみで反映されない。
](https://bit.ly/3mgCpda)

-     Kintoneでチェックボックスを配置。WordPress側への「タグ」に設定
-     添付ファイル(画像)を2枚配置したときの2枚目

**Comment by Gucchiy** [comment]
Sprint2 で修正、クローズします。
