### ISSUE TITLE
サイトに載せたい情報 たたき台

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#15]
サイトにこんなの載せたいな～という、ボヤっとしたレベルで結構ですので、列挙いただけますと幸いです。
固まっていなくても結構です。議論のたたき台になればよいぐらいの粒度となります。
関係団体の興味あるページや、「こんな感じのサイト」など、ほかのサイトへの参考 URL も OK です。
NEO 様活動を象徴する、メッセージ性のあるキーワード、ワーディングなどもあるとより良いです。

**Comment by taeiizuka** [comment]
トップページからユーザー限定のページへ入って、そこでユーザー向けの情報やユーザー同士の交流などできたらいいなあと思います。セキュリティの問題が出てきますので、クリアできる方法があるのかどうか。

**Comment by myama2** [comment]
法人の説明、各事業の説明、情報公開、求人情報は必要です。

**Comment by Gucchiy** [comment]
なるほどですね。
その他、日常のエントリー（blog的なもの）にはどんな記事を書いていくイメージでしょうか？そんなのはそもそもない？

**Comment by myama2** [comment]
日常のエントリーは入れたいのですが、ネオ全体の記事にするか、地活の日々日記だけにするか、そのあたりはこれからの検討事項になると思います。
以下はメモ的ですが、法人⇒制度・雑感・法人日記など、地活⇒地活日記　が今考えられるものです。

**Comment by Gucchiy** [comment]
ログインしたユーザーが見えるページと、そうでないページに分けたい。
以上の要求を Wiki に掲載します。
掲載後、クローズ。

**Comment by Gucchiy** [comment]
以下にサイトコンテンツ 要求事項を記載いたしました。
[サイト コンテンツ 要求事項](https://github.com/Gucchiy/neo/wiki/%E3%82%B5%E3%82%A4%E3%83%88-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84-%E8%A6%81%E6%B1%82%E4%BA%8B%E9%A0%85)

**Comment by Gucchiy** [comment]
@taeiizuka @miura894 

すみません、ログインして、どんな情報を公開したいか、また、ユーザー同士の交流とは具体的にどんなものか（例えば BBS など）をもう少し具体的に教えてくださいませ。

Sprint4 持ち越しとします。

**Comment by genepine** [comment]
@taeiizuka @miura894 @Gucchiy 

> すみません、ログインして、どんな情報を公開したいか、また、ユーザー同士の交流とは具体的にどんなものか（例えば BBS など）をもう少し具体的に教えてくださいませ。
書きご覧ください
https://github.com/Gucchiy/neo/issues/24

**Comment by taeiizuka** [comment]
@Gucchiy @genepine
サイトコンテンツ 要求事項、まとめていただきありがとうございます！
以下、追加事項です。
私の思いつくままに書き出しましたので、山下さん三浦さん何か意見ありましたらお願いします。

”地活コーナー”
・ラルゴだより（毎月発行しているペーパーと同じものを掲載、DLもできる）
・作品ギャラリー（いいね、コメント）

”地活利用者向けコンテンツ”
・イベント、プログラム等の活動日記（写真注文もできる）
・イベント、プログラムへの参加申込状況と申込受付、日程変更等のおしらせ
・意見箱

**Comment by miura894** [comment]
飯塚さんの言われている「写真注文」は地活活動のイベントや旅行の集合写真、個人の顔が映った写真になるのかなと思いますが、集合写真や個人の顔写真がサイト上にのる危険性、安全対策が想像つかないので教えていただきたいです。
(例えばサイト上で守られる方法や、運営でしなければいけない対策などです。)

**Comment by genepine** [comment]
> 飯塚さんの言われている「写真注文」は地活活動のイベントや旅行の集合写真、個人の顔が映った写真になるのかなと思いますが、集合写真や個人の顔写真がサイト上にのる危険性、安全対策が想像つかないので教えていただきたいです。
> (例えばサイト上で守られる方法や、運営でしなければいけない対策などです。)
写真注文に関して
NEOさんが作った、掲載許諾済みの写真アルバムを、NEOさんで注文を受けてイベントごとに販売するなら良いのでは
https://tolot.com/jp/photobook/
500円/1部(税込み)　寄付を付けて1000円とかでも。
注文はKintoneアプリを公開して限定リンクで知らせるなどで

他には外部の共有・プリントサービスを使う。
さらに掲示板機能があれば、サイトには会員登録機能は不要になるでしょう。
ただ注文は共有した相手でおそらく無制限で、どの写真を誰が注文したかはわかりません。
サービスが終わったら終わりますが
https://bit.ly/37HEWY4
https://shashinkan.rakuten.co.jp/share/

**Comment by genepine** [comment]
ストーリーボード的にしてみました
https://miro.com/welcomeonboard/L3OZc340sGxNjeIwQjoCtyKaFpU983Qd1815K1cyMH6nmLCMLWcnJvo3ps2CH3j9

**Comment by genepine** [comment]
NEOさんのテーマカラーはありますか
サイトを作るときは参考に選んでもらってます。
地下鉄色
https://www.colordic.org/m

**Comment by genepine** [comment]
https://www.colordic.org/y
スプリンググリーンspring green #9cbb1c

全国ＪＲ線158路線と新幹線・JRグループカラーコード
https://ayaito.net/webtips/color_code/164/

**Comment by Gucchiy** [comment]
メイン1色と比較する2色の3色セットの候補を5つほどいただければ、色見本作ります。

**Comment by Gucchiy** [comment]
@taeiizuka さん、 @miura894 さん
Kintone から、以下 Wiki の静的ページの項目について、内容を検討の上、Post していただければと思います。

https://github.com/Gucchiy/neo/wiki/%E3%82%B5%E3%82%A4%E3%83%88-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84-%E8%A6%81%E6%B1%82%E4%BA%8B%E9%A0%85

**Comment by genepine** [comment]
画面例
色の設定項目について
https://neo-kintone.sakura.ne.jp/nkwp-swell/wp-content/uploads/2020/12/Image_20201210_103625.png

**Comment by taeiizuka** [comment]
> メイン1色と比較する2色の3色セットの候補を5つほどいただければ、色見本作ります。

①　#64DB8F　#F9F790　#DB7307

②　#9CBB1C　#f5b2b2　#6c3524
　
③　#3eb370　#f8e58c　#93ca76

④　#fcc800　#2ca9e1　#a0d8ef

とりあえず４つ、よろしくお願いします。

**Comment by genepine** [comment]
色見本を作りました
https://github.com/Gucchiy/neo/blob/main/20201215_neo_color_chart.png

SWELLで色を設定する箇所についての記事
https://swell-theme.com/basic-setting/2357/

メインカラー
    見出しや各種ボタンなど、サイトで重要となる様々なポイントで利用される色です。

テキストカラー
    本文中の文字など、サイト全体に適用されるテキストの色

リンクの色
    記事本文中のリンクの文字色

背景色
    サイト全体に渡ってのページ背景色です。

サイトの上部・下部枠の色設定は別々に設定します

サイトに設定したサンプル
https://github.com/Gucchiy/neo/blob/main/20201215_neo_color_chart_web_sample.png
 
> 
> > メイン1色と比較する2色の3色セットの候補を5つほどいただければ、色見本作ります。
> 
> ①　#64DB8F　#F9F790　#DB7307
> 
> ②　#9CBB1C　#f5b2b2　#6c3524
> 　
> ③　#3eb370　#f8e58c　#93ca76
> 
> ④　#fcc800　#2ca9e1　#a0d8ef
> 
> とりあえず４つ、よろしくお願いします。

**Comment by Gucchiy** [comment]
以降、継続的に載せたい内容をご検討ください。
