### ISSUE TITLE
Kintone 承認済みのみ WP に Post するコードの提案

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#16]
Publish Kintone Data 作者様に、今回の掲題対応コードのマージを提案する。

**Comment by Gucchiy** [comment]
返信来ました！

>@gucchiy
>
>ご提案ありがとうございます。
私の案件でも同じような仕様が多々あり、既に kintone_to_wp_kintone_data のフィルターフックを使うことでカスタマイズ可能なようにしております！
>
>kintone_to_wp_kintone_dataフィルターフックで、条件に一致しない場合は空の配列をリターンする処理を書いてもらうと良いかなと思います！
>
>サンプルコードです。
>https://gist.github.com/tkc49/3e8b3b6f92e1e24dfab44a5f5ba1b751

@genepine これって、wp-content\themes\katawara\functions.php に加えれば良いのでしょうか？？

**Comment by Gucchiy** [comment]
サンプルコードの中身：
functions.php
```
<?php
function custom_kintone_to_wp_kintone_data($kintone_data){
  if( strcmp( $kintone_data[‘record’][‘ステータス’][‘value’], ‘承認済み・WEB反映’ ) != 0 ){
    // WPに取り込みたいスタータスではない場合、空の配列をリターンする
    return array();
  }
  
  return $kintone_data;
}

add_filter( 'kintone_to_wp_kintone_data', 'custom_kintone_to_wp_kintone_data' );
```

**Comment by genepine** [comment]
@Gucchiy 

> これって、wp-content\themes\katawara\functions.php に加えれば良いのでしょうか？？
wp-content\themes\**katawara-child**\functions.php　に加えてください。

**Comment by Gucchiy** [comment]
対応済みです。12/2 の定例でクローズしましょう。
