### ISSUE TITLE
Wordpress Theme のご提案と事例提示

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#17]
良さげな Wordpress Theme のご提案と事例の提示

**Comment by genepine** [comment]
WordPressテーマ Katawara 事例集です
[https://oozusc.com/](https://oozusc.com/)
[https://shun-ran.net/](https://shun-ran.net/)
[https://syncom-p.com/](https://syncom-p.com/)
[https://consulting.seeds-c.com/](https://consulting.seeds-c.com/)
[http://sk8-life.info/](http://sk8-life.info/)

**Comment by genepine** [comment]
WordPressテーマ SWELL 事例集です
[https://www.hug-matsu.jp/](https://www.hug-matsu.jp/)
[https://www.buntakun.com/](https://www.buntakun.com/)
[https://teradashokai.co.jp/](https://teradashokai.co.jp/)
[https://komakici.jp/](https://komakici.jp/)

**Comment by genepine** [comment]
WordPressテーマ Lightning 事例集です
https://themesinfo.com/lightning_child-wordpress-theme-b5qp/4/

**Comment by Gucchiy** [comment]
これらの中で、以下のサイトが一番しっくりくるそうです。
https://komakici.jp/
ポイントは、ナビゲーション メニューだけで、サイト全体に何があるか一望できる。
縦メニューより横メニューの方がよい？

**Comment by genepine** [comment]
> これらの中で、以下のサイトが一番しっくりくるそうです。
> https://komakici.jp/

テーマは SWELL (有料版無料版はわかりません)
ただし、レイアウト用のプラグインに別のテーマ、Snow Monkey併用推奨の[Snow Monkey Blocks](https://ja.wordpress.org/plugins/snow-monkey-blocks/)を使っている。


> ポイントは、ナビゲーション メニューだけで、サイト全体に何があるか一望できる。
Katawaraの場合はトップの写真の高さを低すれば調整できるかも

> 縦メニューより横メニューの方がよい？
メニューやコンテンツ
表示はスマホ前提で考えるのが良いかもしれません。
PC前提で相手に説明すると、あれ何処に乗ってます？という話になりがち。

**Comment by genepine** [comment]
テーマ　SWELLを使う場合、私は購入したものを使っています。
無料版で何処まで機能が減るのか把握できていません。
ですので有利版を購入頂くか、費用折半かと思っています。

**Comment by Gucchiy** [comment]
- どれを選ぶとしても、テーマの Version Up でレイアウトがずれるなどのメンテナンスは必要になる可能性はある。

- 横メニュー
  - SWELL
     - 買い切り \17,600 (税込み）
        - 松野さんが制作会社としてライセンスしているので、NEO 様にはそのライセンスで使えるっぽい
     - Version Up もできる
     - 別途、カスタム フィールドの場所を調べないといけない（追加開発）

  - Lightning
     - 年間の fee になる
     - Version Up が早い
     - 無料版もあるが、どの程度の制限か確認していない（レイアウトのカスタマイズが大変になる）

- 縦メニュー
  - Katawara
     - 無料
     - 見た目縦メニューで内部的に Lightning
     
上記検討より、Katawara で実装済みである、カスタムフィールドの実装を Swell で実現できるか確認が必要。
Swell で画像表示ができるようにする、など。結構やることある。
→ Swell の検討を行う

**Comment by Gucchiy** [comment]
Swell 用別プロトタイプ フォルダを作り、比較検討できるようにします。

**Comment by Gucchiy** [comment]
SWELL で決定
