### ISSUE TITLE
公開した記事を修正する場合

### ISSUE THREAD

**Issue by myama2** [Gucchiy/neo#19]
- [ ] wpに公開した記事を修正するとどうなるかの検証

**Comment by myama2** [comment]
kintoneの記事を更新した時点でwpも変更される。
承認フローを通らない。

**Comment by myama2** [comment]
kintoneのプロセス管理を変更
承認済み・WEB反映から再提出できるようにプロセスを追加

**Comment by myama2** [comment]
プロセスに再提出を追加したが、
承認フローを通らずに更新されてしまう。

**Comment by Gucchiy** [comment]
こちらは、staff から、ステータスが「承認済み・WEB反映」の状態のまま、編集、保存すると、承認状態にならないため、そのまま WP に反映されます。一旦、「修正して再提出する」ボタンを教え頂いた後であれば、その後の編集結果は chief による承認が行われない限り反映はされません。

**Comment by Gucchiy** [comment]
これは、WP 側は、送られてきた文書が、初めて「承認済み・WEB反映」ステータスになったのか、二回目以降の「承認済み・WEB反映」ステータスになったのかを判断できないことに由来します。
一度、承認済み・WEB反映として保存したら、ステータスを「修正して再提出する」に kintone 側でしてくれると解決できるのですが、kintone のステータス設定にそういう設定はないでしょうか？

**Comment by myama2** [comment]
@Gucchiy さん、kintoneのプロセスを変更しました。
なのですが、これだとダメなようですか。
新規作成→提出→チーフが承認（ここでwpを更新)→再編集→再提出→チーフが承認(ここでwpを更新)→再編集に戻ることができる
現状では、再編集終了時にwpに反映されます。
「承認済み・WEB反映」ステータスは再編集後のフックにも変化無くあがってくる感じでしょうか。

**Comment by Gucchiy** [comment]
ご提示いただいている、プロセスで、「再編集」とあるところをスタッフが行うかと思うのですが、この時、文書のステータスが「承認済み・WEB反映」になっていることが問題です。この状態で保存すると、WP に「承認済み・WEB反映」ステータスとしてデータをポストしてしまうのです。
以下、承認後に、スタッフが該当エントリーを表示した画面です。

<img width="677" alt="スクリーンショット 2020-11-29 19 18 18" src="https://user-images.githubusercontent.com/2966953/100539166-dc182900-3277-11eb-99ee-f65fd1733623.png">

つまり、最初の「チーフが承認」した後、なんだかの方法でステータスを「承認済み・WEB反映」＊以外＊にすれば良いわけです。なんだか設定する方法はないでしょうか？

**Comment by Gucchiy** [comment]
フローをもう一度眺めていて、ちょっと思い付いたんですが、chief による承認のタイミング以外では WP に POST する必要がなさそうな感じですね。あ、削除だけはありますかね。WebHook のタイミングを、ステータス更新とレコードの削除だけにすれば、解決できそうな気がしてきました。ちょっと実験してみましょう。とりあえず、上記２つだけの設定にしてみます

**Comment by Gucchiy** [comment]
@myama2 うまく動いている気がします！今一度、フローを確認してみていただいてよろしいですか？

**Comment by myama2** [comment]
@Gucchiy さん
初投稿、承認、再編集1、承認、再編集2、承認、削除まで、フローを確認しました。
結果、要求通りです。
つまるところwebhookの保存時のチェックを外したということですね。
他に影響が出ていないようであればバッチリです。

**Comment by Gucchiy** [comment]
了解です！では、一旦、こちらで様子を見てみましょう。

**Comment by Gucchiy** [comment]
本件、修正済みのため、クローズといたします。
