### ISSUE TITLE
kintone で公開処理した際、WP上では承認なしで公開したい

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#2]
kintoneで公開処理をすると、wpでは再度の承認無しで公開されればいいですね。「デフォルトでは下書き」とありますので、可能なのでしょうか。そうすると、画像無限増殖も回避できるような気がしました。

**Comment by Gucchiy** [comment]
以下、松野さんのコメントより：
> 「デフォルトでは下書き」と「画像無限増殖」加えて「投稿が初期状態で無名」はこのプラグインの作者の方にご対応いただいて、回避策があります。来週以降に加えます。

**Comment by genepine** [comment]
WP側 テーマ functions.php にコードを追加する
https://wordpress.org/support/topic/%e3%80%90%e4%b8%8b%e6%9b%b8%e3%81%8d%e3%80%91%e4%bf%9d%e5%ad%98%e3%82%92%e3%80%90%e5%85%ac%e9%96%8b%e3%80%91%e3%81%a7%e4%bf%9d%e5%ad%98%e3%81%95%e3%82%8c%e3%82%8b%e3%82%88%e3%81%86%e3%81%ab%e5%a4%89/

**Comment by Gucchiy** [comment]
11/16の週には作業完了の見込み

**Comment by genepine** [comment]
Publish kintone data で【下書き】保存を【公開】で保存されるように変更
しかし #12 ユーザー staffで「保存のみ」で記事がWordPress側に送られる
そのため、承認なしで公開されてしまう。#12 のKintone側Webhookの設定を変更、要仕様・動作確認

**Comment by genepine** [comment]
直接投稿にするとWP側でもう一度更新しないと画像が表示されない

**Comment by genepine** [comment]
> #8 WP側投稿が初期状態で無名 と
> #2 kintone で公開処理した際、WP上では承認なしで公開したい
> #7 が画像増殖と関連がある気がするので着手します

関連性はなかった

**Comment by Gucchiy** [comment]
#12 が未達なので、本ユーザーシナリオは完成していません。Sprint2 に持ち越しとします。

**Comment by Gucchiy** [comment]
#12 も修正されたので、本件クローズとします。
