### ISSUE TITLE
画像以外のファイル添付

### ISSUE THREAD

**Issue by myama2** [Gucchiy/neo#20]
画像以外のファイル添付
wpには反映されない

**Comment by myama2** [comment]
例えば、チラシPDFや財務諸表等を掲載したい場合、kintoneからできない。

**Comment by Gucchiy** [comment]
pdf や、xlsx などの添付が可能か、確認する。Sprint4 以降。

**Comment by Gucchiy** [comment]
検証結果としては、添付ファイル自体は WP に転送されているが、HTML としてリンクされない、ということだったようです。Template 側か、Plug In 側か分からないのですが、やりようがあるような気がしますね。

**Comment by genepine** [comment]
テーマ側テンプレートに表示用のphpを記載すれば可能です。
https://zxcvbnmnbvcxz.com/wordpress-%e3%82%bf%e3%82%b0%e3%83%a1%e3%83%a2%e2%91%a1/
```
<?php
$pdfpath = get_post_meta($post->ID, "パンフレットPDF", false);
foreach($pdfpath as $pdfpath){
    $pdfpath = wp_get_attachment_url($pdfpath);
}
?>
<a href="<?php echo $pdfpath ?>" target="_blank">パンフレットが見れます</a>
```

**Comment by myama2** [comment]
> テーマ側テンプレートに表示用のphpを記載すれば可能です。
コードを見る限り、添付ファイルを毎回指定したコードを記載する必要があるのでしょうか？
> "パンフレットPDF"

**Comment by genepine** [comment]
投稿のたびに毎回コードを書く必要はありません。
パンフレットが見れます　の部分をファイル名表示にすることで、毎回違った表示にできます。

**Comment by Gucchiy** [comment]
ファイルをいくつまで載せたいか？ → 多くは PDF。年次総会の報告書などはどうなるか？
5種類ぐらいあったりする。バラバラに載せたいなどのニーズはないか？
イベントの申込書？

一旦、pdf 4枚までを仕様とする。

**Comment by genepine** [comment]
お知らせか、ファイル名をリンクにするコード
` 
<div class="wp-kintone-pdf">
<?php
	$pdfpath = get_post_meta( $post->ID, "attachment_pdf_01", false );
	foreach ( $pdfpath as $pdfpath ) {	
　　$pdfpath = wp_get_attachment_url( $pdfpath );
　　}
?>
<p><a href="<?php echo $pdfpath ?>" target="_blank">パンフレットが見れます01-ファイル名表示</a></p>
<?php $filename = basename( $pdfpath );?>
<p><a href="<?php echo $pdfpath ?>" target="_blank"><?php echo $filename ?></a></p>
</div>
`

**Comment by genepine** [comment]
値がなかった場合に、リンクが表示されてしまうので例外処理を追加
```
<div class="wp-kintone-pdf">
<?php
	$pdfpath = get_post_meta( $post->ID, "attachment_pdf_01", false );
	if(empty($value)):?>
    <!--★ここは空欄だった場合に表示されます(空でOK)。-->
<?php else:?>	
		<?php foreach ( $pdfpath as $pdfpath ) {
		$pdfpath = wp_get_attachment_url( $pdfpath );
		}
	?>
	<p><a href="<?php echo $pdfpath ?>" target="_blank">パンフレットが見れます01-ファイル名表示</a></p>
	<?php $filename = basename( $pdfpath );?>
	<p><a href="<?php echo $pdfpath ?>" target="_blank"><?php echo $filename ?></a></p>
<?php endif;?>
</div>
```

**Comment by Gucchiy** [comment]
Sprint6 で確認後、クローズ

**Comment by genepine** [comment]
値がなかった場合に、リンクが表示されてしまう例外処理を修正
```
<div class="wp-kintone-pdf">
	<?php $pdfpath = get_post_meta($post->ID, 'attachment_pdf_02', true);?>
		<?php if(empty($pdfpath)):?>
			<?php else:?>
			<?php
				$pdfpath = get_post_meta( $post->ID, "attachment_pdf_02", false );
				foreach ( $pdfpath as $pdfpath ) {
				$pdfpath = wp_get_attachment_url( $pdfpath );
				}
			?>
		<?php $filename = basename( $pdfpath );?>
			<p><a href="<?php echo $pdfpath ?>" target="_blank"><?php echo $filename ?></a></p>
		<?php endif;?>
</div>
```

**Comment by genepine** [comment]
全部投稿済み投稿
https://neo-kintone.sakura.ne.jp/nkwp-swell/?p=952

**Comment by Gucchiy** [comment]
実装確認完了のためクローズ
