### ISSUE TITLE
画像添付への複数枚の投稿

### ISSUE THREAD

**Issue by myama2** [Gucchiy/neo#21]
kintoneでは添付ファイルに複数ファイルを添付できますが、
wpには一枚目のみアップされる。

**Comment by myama2** [comment]
kintoneで1枚のみにする設定がないので、運用で注意を喚起するしかない。

**Comment by Gucchiy** [comment]
添付ファイル1、添付ファイル2それぞれに複数のデータを入れることができる。Publish Kintone Data でどこまで対応できるのか確認。Sprint4 で対応。

**Comment by Gucchiy** [comment]
@genepine これって、仕様なんでしたっけ？もし把握されているようでしたらご確認いただけますと幸いです！

**Comment by myama2** [comment]
kintoneの仕様で添付ファイルは複数ファイルを登録できます。
https://jp.cybozu.help/k/ja/user/app_settings/form/form_parts/attachment.html
可能なら、添付ファイル１、添付ファイル２ではなく、
添付ファイル１で複数ファイルを登録できれば良いのですが。

**Comment by genepine** [comment]
> 可能なら、添付ファイル１、添付ファイル２ではなく、
> 添付ファイル１で複数ファイルを登録できれば良いのですが。

Kintoneの仕様を知らなかったので、添付ファイル欄を複数置きました
Publish-kintone-dataの仕様
Kintone側の添付ファイルは、WordPress側の一つのカスタムフィールドに割り当てます。
複数ファイルを送ったときの、WordPress側で受け取るコードが書けるかわかりません。

**Comment by genepine** [comment]
メモ
1つの名前に登録された複数の値を出力する
http://wpcj.net/1437#1
画像を横並びにしたい場合、
画像とPDF(各種ファイル)を置いた場合はフィールド(kintone側添付ファイル)を分けるほうが　レイアウトの自由度がある

**Comment by Gucchiy** [comment]
送られるカスタム・フィールドの実装が複雑になりそう。
また、複数枚となった場合の、表示側のレイアウトも検討が必要となる。

表示する写真は4枚までとかの方が blog 的にもむしろいいのではないか？
公開用途であるため、一旦、仕様を4枚までとする。

**Comment by Gucchiy** [comment]
Sprint6 にて状況確認予定。

**Comment by Gucchiy** [comment]
とりあえず、４枚で承認

**Comment by genepine** [comment]
Kintone側一覧画面（すべて）で希望通りの順番にならんでいない
@myama2 Kintone側一覧画面は別途作る

**Comment by genepine** [comment]
https://www.bing.com/search?q=%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%A7%E8%A4%87%E6%95%B0%E7%94%BB%E5%83%8F%E3%81%AE%E8%A1%A8%E7%A4%BA&FORM=ANCMS9&PC=U531

**Comment by genepine** [comment]
https://memocarilog.info/wordpress/theme-custom/3200

**Comment by genepine** [comment]
Custom Field Templateを使用し
設定画面の
Auto Hook of `the_content()` (Experimental Option)
へ
オプション
コンテンツの後　で
下記のコードを記入する。テーマに依存しなくなる。
https://begeeek.com/article/594/

````
<h3>ギャラリー</h3>
<?php
	$imgsize = "medium";
	$productimgs = post_custom('attachment_01');
	if($productimgs){
		if(is_array($productimgs)){
		foreach($productimgs as $perimg){
		$productImg = wp_get_attachment_image_src($perimg, $imgsize);
		list( $url, $w, $h) = $productImg;
?>
		<img src="<?php echo $url; ?>">
<?php
			}
		}else{
			echo wp_get_attachment_image($productimgs); 
		}
	}
?>
````
