### ISSUE TITLE
WordPressのコメント機能を使うか否か

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#22]
WordPressに投稿した日記に対して、11/29現在WordPressの機能で、閲覧者からコメントができます。
最近はこのコメント機能は使わない人が多いです。コメントがあるとWordPressにログインして、表示許可や返信など随時対応の必要があります。
この点についてコメント機能を使うか否か検討、と思います。

**Comment by myama2** [comment]
基本的には、WordPressでの操作は行わない（行えない？）ので、コメント機能は無しで良いと考えます。
おそらく、表示許可や返信が随時できないので、コメントいただいた人に失礼をしてしまうと思います。

**Comment by Gucchiy** [comment]
不要とのことで、クローズといたします。
