### ISSUE TITLE
サイトコンテンツ 要求事項に従ってのポスト

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#23]
[サイトコンテンツ 要求事項](https://github.com/Gucchiy/neo/wiki/%E3%82%B5%E3%82%A4%E3%83%88-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84-%E8%A6%81%E6%B1%82%E4%BA%8B%E9%A0%85) に従って、文書を検討、Kintone から Post してみてください。 飽くまでテストとなりますが、検討いただいた書面はそのまま使える可能性もありますので、実際の公開を意識して文書をご検討いただければと思います。

**Comment by myama2** [comment]
テストkintoneではタグがカレーとラーメンですが、増やしても良いですか？

**Comment by Gucchiy** [comment]
はい、そう言った通常利用での課題を洗い出す意図もありますので、さまざま必要な設定を追加いただければと思います！

**Comment by Gucchiy** [comment]
Post のテストは実施いただいたため、クローズ
