### ISSUE TITLE
静的ページの実現方法検討

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#25]
[サイトコンテンツ 要求事項](https://github.com/Gucchiy/neo/wiki/%E3%82%B5%E3%82%A4%E3%83%88-%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84-%E8%A6%81%E6%B1%82%E4%BA%8B%E9%A0%85) によると、静的ページがあります。最悪 WP の静的コンテンツの扱いで良いと頂いていますが、Kintone からの更新方法があるか、検討する。

**Comment by Gucchiy** [comment]
@genepine カテゴリーを更新ページと、静的ページに分けて、Template 側でカテゴリーで振り分けるのが良いのかな、と思っているのですが、どうでしょう？コメントくださいませ。

**Comment by genepine** [comment]
> @genepine カテゴリーを更新ページと、静的ページに分けて、Template 側でカテゴリーで振り分けるのが良いのかな、と思っているのですが、どうでしょう？コメントくださいませ。
すみません、理解が及ばないので詳細説明をお願いします。

**Comment by genepine** [comment]
以後、WordPress的に言い換えます
更新ページ=投稿ページ
静的ページ=固定ページ

Publish-kintone-data仕様
投稿ページを書き換えるのはできます
　投稿ページに「カスタムポストタイプ(例えば、今後の予定)」を作り、それを切り替えて投稿することはできます。しかし投稿の対象は一つ。
固定ページを書き換えるのはできない。

固定ページをKintoneで書き換えることができた場合
WordPress・テーマの利点やデザイン的要素(レイアウト等)が失われると思います。

**Comment by myama2** [comment]
> 固定ページをKintoneで書き換えることができた場合
> 
>     * Kintone側アプリにWordPress側の新規固定ページ作成・削除や、どのページを書き換えるか　追加する必要がある
これは、カテゴリー等に追加すればできるような気がしますが、

>     * WordPress・テーマの利点やデザイン的要素(レイアウト等)が失われると思います。
これを考えると、kintoneでの入力・更新・削除は不要かなと思います。
固定ページ自体は年に数回ぐらいの書き換えなので、むしろWPでエディットする方が良いと思います。

**Comment by genepine** [comment]
言葉足らずでした
まず
WordPressのページには下記の2種類があり、扱いがそもそも違います。

-     更新ページ=投稿ページ
-     静的ページ=固定ページ 

次に
Publish-kintone-data仕様

-     固定ページを書き換えるのはできない。

が前提でさらに　改変が必要です

- Kintone側アプリにWordPress側の新規固定ページ作成・削除や、どのページを書き換えるか　追加する必要がある
- Publish-kintone-dataにも固定ページ投稿の受け側の仕組みを入れる必要がある

**Comment by Gucchiy** [comment]
そうですね、kintone からの post はレイアウトなどの制約が出るので、そこを割り切れるかどうか、というのも判断の一つになるかと思いました。はい、WP の静的ページが別ものであることは理解できています。

私が、カテゴリー等で追加しちゃえばいいのかな、と思ったのは、次のような感じです。
まず、Post 時に、更新ページか、固定ページ用か、カテゴリーを分けます。ここでいう「固定ページ」は WP の静的ページの意味ではなく、投稿ページとして post されるけど、扱いとして固定ページにする、という意味です。

WP では、更新ページをカテゴリーごとに分けることができたと思うので、固定ページ用カテゴリーの更新ページを、運用上「固定ページ」として表現してしまえばよいかと思ったわけです。どうでしょうか？

**Comment by genepine** [comment]
> WP では、更新ページをカテゴリーごとに分けることができたと思うので、固定ページ用カテゴリーの更新ページを、運用上「固定ページ」として表現してしまえばよいかと思ったわけです。どうでしょうか？

「固定ページ」は使わずに「投稿ページ」でサイト全体を構成するのですね。わかりました。
例
kintone側カテゴリ
日記(投稿扱い)
今後の予定(投稿扱い)
わたしたちについて(固定ページ扱い)
求人情報(固定ページ扱い)

WordPress側メニュー
わたしたちについて
求人情報

トップページの投稿リスト
日記
今後の予定

**Comment by Gucchiy** [comment]
はい、一つのアイディアです。例示いただいている通りです。ただし、レイアウトなどの制約があるので、そのあたりが判断ポイントになりそうですね

**Comment by genepine** [comment]
投稿を投稿ページカテゴリと固定ページカテゴリに分けると、数の少ない固定ページカテゴリが埋もれて編集しにくくなるかな、と思いました。

**Comment by Gucchiy** [comment]
@myama2 さん、本件、Kintone からの post を行うと、レイアウトの確認ができないなど、できないことが多い割に、kintone から入力するメリットが少ないため、WP の静的ページを編集頂きたく考えています。コメント頂ければ幸いです。

**Comment by myama2** [comment]
@Gucchiy さん
静的ページ（固定ページ）はWPで作成するようにします。
確か法人紹介ページはサンプルで作成しています。
