### ISSUE TITLE
「塗りつぶし」が WP 公開画面で反映されない

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#26]
トラブル原因が違ったため

「塗りつぶし＋文字拡大」が WP 公開画面で反映されない https://github.com/Gucchiy/neo/issues/4

を分割
Publish-kintone-data作者様に[報告修正いただいた](https://wordpress.org/support/topic/kintone%e5%81%b4rich-text-form%e3%81%ae%e6%96%87%e5%ad%97%e8%89%b2%e3%83%bb%e8%83%8c%e6%99%af%e8%89%b2%e3%81%8c%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84/)

1.9.2では同様に下書き時(のプレビュー)に反映されない項目があった

- Kintoneでチェックボックスを配置。WordPress側への「タグ」に設定
- 添付ファイル(画像)を2枚配置したときの2枚目

    が解消

**Comment by Gucchiy** [comment]
パターンの掲載、
プロトタイプサイトにデプロイ、
確認後クローズ
Sprint5

**Comment by Gucchiy** [comment]
Sprint6 で確認後クローズとします。

**Comment by genepine** [comment]
修正確認しました
https://neo-kintone.sakura.ne.jp/nkwp-swell/?p=944
