### ISSUE TITLE
「文字拡大」が WP 公開画面で反映されない

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#27]
トラブル原因が違ったため

「塗りつぶし＋文字拡大」が WP 公開画面で反映されない https://github.com/Gucchiy/neo/issues/4
を分割

Publish-kintone-dataで[KintoneがWordPress側に送信したHTMLタグがCSS3で非推奨要素](https://github.com/Gucchiy/neo/wiki/WordPress%E3%81%AB%E5%87%BA%E5%8A%9B%E3%81%97%E3%81%9FKintone%E3%81%AERich-Text-form-%E3%81%AEHTML%E3%82%BF%E3%82%B0%E8%A7%A3%E6%9E%90%E7%B5%90%E6%9E%9C)になっていた。

WordPress子テーマ側のCSSを上書き修正することで対応できる。

修正前の送信結果
```
<div><font size="1">フォントサイズ小さい</font></div>
<div><font size="2">普通のテキスト</font></div>
 文字を選択してから「普通」を選択すると<font size="2">が指定される
<div><font size="4">フォントサイズやや大きい</font></div>
<div><font size="6">フォントサイズ大きい</font></div>

```
修正後対策(Katarawaテーマ) CSS
class .p-entry-content はテーマによって異なるので注意。

```
.p-entry-content font[size="1"]{
	font-size :80%;
}
.p-entry-content font[size="2"]{
	font-size :100%;
}
.p-entry-content font[size="4"]{
	font-size :120%;
}
.p-entry-content font[size="6"]{
	font-size :200%;
}

```

**Comment by Gucchiy** [comment]
ご対応ありがとうございます。
12/9 付け mtg にてクローズ承認。

**Comment by Gucchiy** [comment]
テーマ設定、CSS 設定後対応予定。
その後クローズ。
Sprint5

**Comment by genepine** [comment]
対策として、テーマごとの投稿表示欄のclassで範囲を指定する方法を取っていました
しかし、最近のテーマでは他にfontタグを使うことがないので、範囲を指定せず直接書きます。
```
font[size="1"]{
	font-size :80%;
}
font[size="2"]{
	font-size :100%;
}
font[size="4"]{
	font-size :120%;
}
font[size="6"]{
	font-size :200%;
}

```

**Comment by Gucchiy** [comment]
修正確認済み
