### ISSUE TITLE
WordPressで表示される、エラーのまとめ

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#29]
メディアライブラリ　枠
左側1列縦で小さく
Failed to initialize plugin: LoosButtons
と表示されるが、ACFが原因かもとのこと
https://u.swell-theme.com/community/swell-bugs/%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%A7%E3%82%A2%E3%83%A9%E3%83%BC%E3%83%88%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B/
対応不要

**Comment by genepine** [comment]
SWELL?
カスタマイザー＞メニュー　のページ一覧に(旧エディター)と表示されます
が作成しているページはブロックエディタ
表示上の問題なので対応不要

**Comment by Gucchiy** [comment]
Sprint6 にて確認

**Comment by Gucchiy** [comment]
FAQ として残す。

**Comment by Gucchiy** [comment]
[FAQ として記載しました](https://github.com/Gucchiy/neo/wiki)。クローズします。

**Comment by genepine** [comment]
> メディアライブラリ　枠
> 
> 左側1列縦で小さく
> 
> Failed to initialize plugin: LoosButtons
> 
> と表示されるが、ACFが原因かもとのこと
> 
> https://u.swell-theme.com/community/swell-bugs/%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%A7%E3%82%A2%E3%83%A9%E3%83%BC%E3%83%88%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%82%8B/
> 
> 対応不要

[SWELL ver.2.3.2で修正されました](https://bit.ly/3ctoTB7)
