### ISSUE TITLE
Kintoneで記事を書いたら提出を忘れる

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#30]
Kintoneで記事を書いたら提出を忘れる

**Comment by myama2** [comment]
これは確かkintoneでリマインド設定ができたと思います。
記事作成後未提出で日数経過後リマインド、決裁しないで日数経過後リマインド・・・
このような感じの設定方法調べておきます。

**Comment by genepine** [comment]
スタッフで記事を書いて保存
チーフでログインしたら記事が来ていない。なぜ？
と数分悩み、スタッフで提出してないから、となりましたので。

**Comment by Gucchiy** [comment]
Sprint6 にて確認

**Comment by Gucchiy** [comment]
保存では不十分で、提出する、をやり忘れる可能性について FAQ 化する。

**Comment by Gucchiy** [comment]
[Wiki に FAQ を記載済み](https://github.com/Gucchiy/neo/wiki)。クローズします。
