### ISSUE TITLE
画像投稿時、WP側投稿一覧でアイキャッチが初回のみ表示されないが、画面切り替えで表示される

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#31]
画像投稿時、WP側投稿一覧でアイキャッチが初回のみ表示されないが、画面切り替えで表示される
この仕様で問題ないか確認
functions.php/Publish Kintone Data Options Plugin #32 でも挙動は同じ

**Comment by Gucchiy** [comment]
Sprint6 で確認

**Comment by Gucchiy** [comment]
複数マシンの実験では再現せず。アイキャッチ等の画像が表示されない不具合が出てくるようであれば、お知らせください。

**Comment by Gucchiy** [comment]
[FAQ として残しました](https://github.com/Gucchiy/neo/wiki/)。クローズします。
