### ISSUE TITLE
「塗りつぶし＋文字拡大」が WP 公開画面で反映されない

### ISSUE THREAD

**Issue by Gucchiy** [Gucchiy/neo#4]
「塗りつぶし＋文字拡大」について
kintoneとＷＰ投稿を編集 では「塗りつぶし＋拡大」で表示されているのですが、公開画面では拡大されていませんでした・・・。装飾を重ねるとうまくいかないのでしょうか。タイムラグでしょうか。
後、「投稿した人」が現状同一人物のような印象ですが、個人までは特定せずとも投稿元をkintoneで選択できれば・・・と感じました。

**Comment by Gucchiy** [comment]
以下、松野さんコメントより：

> 文字装飾については調べます。
投稿した人は、現状、管理者が承認してWordPress側でも投稿した人が一人です。
これは日記をNEOさん名義のみで書くのか、NEOの誰々さんが書きました、などと署名を入れるのか決める必要があります。
また投稿者の複数選択はWordPress側の機能の追加が必要です。

**Comment by genepine** [comment]
WP側で更新のたびにメディアライブラリ画像が無限増殖する
[https://github.com/Gucchiy/neo/issues/7](url)
の対策でクラシックエディターを入れるのでその状態でテストする

**Comment by genepine** [comment]
<font size="6"><b>楽しみ</b></font>
*{
    font-size: 100%;
 }
消す
か Kintone側のリッチエディタの文字の大きさ変更の仕様についてkintoneに質問する

**Comment by genepine** [comment]
<font>タグがあったらサイズを指定するCssを書く必要がある。
しかしいつ<font>タグが出てくるかわからないので実装や実際の処理が重い。

**Comment by Gucchiy** [comment]
WP Theme 側の CSS で、font と size 属性の値をセレクタでひっかけて、サイズ応じて font-size 指定とかできないでしょうかねー

**Comment by genepine** [comment]
装飾ごとに、出力されているhtmlタグを調べる。

**Comment by genepine** [comment]
> WP Theme 側の CSS で、font と size 属性の値をセレクタでひっかけて、サイズ応じて font-size 指定とかできないでしょうかねー

これでしょうか

https://www.conifer.jp/csstest/css-huriwake.html

**Comment by Gucchiy** [comment]
> > WP Theme 側の CSS で、font と size 属性の値をセレクタでひっかけて、サイズ応じて font-size 指定とかできないでしょうかねー
> 
> css でif文を使う　これでしょうか
> 
> https://www.conifer.jp/csstest/css-huriwake.html

はい、理屈的には上記を使えば、すべてのタグ＋属性に対して見栄えを揃えることは可能だと思います。後はメンテナンス性ですよねー。テーマもアップデートされますけど、そこを割り切るのかどうか。

**Comment by genepine** [comment]
#

> > > WP Theme 側の CSS で、font と size 属性の値をセレクタでひっかけて、サイズ応じて font-size 指定とかできないでしょうかねー
> > 
> > 
> > css でif文を使う　これでしょうか
> > https://www.conifer.jp/csstest/css-huriwake.html
> 
> はい、理屈的には上記を使えば、すべてのタグ＋属性に対して見栄えを揃えることは可能だと思います。後はメンテナンス性ですよねー。テーマもアップデートされますけど、そこを割り切るのかどうか。

テーマのアップデートに影響しない、カスタマイズ用の子テーマを作る方法があります。
Kintone側で古いタグ、変なタグを出力している箇所のみCSSを書いておくのが良いですね。
Kintone 側が変わると大変ですが…

**Comment by Gucchiy** [comment]
一旦、どのようなタグが Kintone から出力されるか、一般的な記述の範囲（<b> や <font> など）でご確認いただけますと幸いです！

**Comment by genepine** [comment]
KintoneのRich Text Formの内容をPublish Kintone Data でWordPressに送った時のHTMLタグについてまとめました(長い)
https://github.com/genepine/Publish-kintone-data-rich-txt-html-tag/wiki
アンダーライン <u>タグ　非推奨要素 http://www.htmq.com/html/u.shtml
文字色・背景色　反映されない
文字の大きさ <font>タグ　非推奨要素 http://www.htmq.com/html/font.shtml
打ち消し線 <strike>タグ　非推奨要素 http://www.htmq.com/html/strike.shtml
反映されるもの、反映されないものを組み合わせ　ダメなものはだめでした

**Comment by genepine** [comment]
文字色・背景色　反映されない　について
Kintoneで保存・承認フローを完了にしても反映されない
しかしWordPress側のPublish Kintone Data の機能でBulk Updateすると反映される
<div><span style="background-color:rgb( 255 , 0 , 0 )">背景色</span></div>

**Comment by genepine** [comment]
ログでは色が送られている
```
    array (
      'type' => 'RICH_TEXT',
      'value' => '<div><span style="color:rgb( 255 , 0 , 0 )">文字色赤</span><br /></div>',
    ),
```

**Comment by genepine** [comment]
質問しました
[KintoneアプリRich Text formの文字色・背景色が<span>タグのみで反映されない](https://wordpress.org/support/topic/kintone%e5%81%b4rich-text-form%e3%81%ae%e6%96%87%e5%ad%97%e8%89%b2%e3%83%bb%e8%83%8c%e6%99%af%e8%89%b2%e3%81%8c%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84/)

**Comment by genepine** [comment]
Publish Kintone Dataの作者に対応いただきました
- 1. kintoneのリッチエディターで保存した文字色・背景色が下書きに反映された
- 2. 組み合わせ　文字色赤-背景色黄もできました
と同時に1.9.2では同様に下書き時(のプレビュー)に反映されない項目があったがこの更新で解消した
-     Kintoneでチェックボックスを配置。WordPress側への「タグ」に設定
-     添付ファイル(画像)を2枚配置したときの2枚目

**Comment by Gucchiy** [comment]
@genepine  Publish Kintone Data 作者様にご対応いただく部分、CSS の追加でご対応いただく部分で Issue を分けて頂いたのちにクローズといたします。

**Comment by Gucchiy** [comment]
上記、 @genepine さんと相談します。Sprint4

**Comment by genepine** [comment]
本件分割
「塗りつぶし」が WP 公開画面で反映されない #26 
「文字拡大」が WP 公開画面で反映されない #27

**Comment by Gucchiy** [comment]
それぞれ、Issue に分割されましたので、こちらはクローズといたします。
