### ISSUE TITLE
上部 Navigation変更

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#58]
上部 Navigation
	- home ネオについて 支援内容 blog お問い合わせ 検索 ->
	- home 支援内容 ネオについて 採用情報 ネオ日記 お問い合わせ 検索
	- blog ページ、タイトル ⇒ ネオ日記

**Comment by genepine** [comment]
- home ネオについて 支援内容 blog お問い合わせ 検索 ->
- home 支援内容 ネオについて 採用情報 ネオ日記 お問い合わせ 検索
済
- blog ページ、タイトル ⇒ ネオ日記
済

**Comment by Gucchiy** [comment]
修正確認済み、Close します。
