### ISSUE TITLE
WP側【下書き】保存を【公開】で保存されるように変更

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#6]
WP側 functions.php にコードを追加する
[https://wordpress.org/support/topic/%e3%80%90%e4%b8%8b%e6%9b%b8%e3%81%8d%e3%80%91%e4%bf%9d%e5%ad%98%e3%82%92%e3%80%90%e5%85%ac%e9%96%8b%e3%80%91%e3%81%a7%e4%bf%9d%e5%ad%98%e3%81%95%e3%82%8c%e3%82%8b%e3%82%88%e3%81%86%e3%81%ab%e5%a4%89/](url)

**Comment by genepine** [comment]
重複しました

**Comment by Gucchiy** [comment]
Close 処理は neo 様のご確認を取ったうえで行わせてくださいませ！（こちらは重複なのでさして重要ではありませんが）

**Comment by Gucchiy** [comment]
こちらも 11/18 付け定例にてクローズ確認
