### ISSUE TITLE
WP側投稿が初期状態で無名

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#8]
WPテーマ側 functions.phpにコードを追加する
[https://wordpress.org/support/topic/%e6%8a%95%e7%a8%bf%e8%80%85%e3%81%8c%e7%a9%ba%e6%ac%84%e3%81%ae%e3%81%9f%e3%82%81%e3%81%ab%e3%81%8a%e3%81%9d%e3%82%89%e3%81%8f%e8%b5%b7%e3%81%8d%e3%82%8b%e5%95%8f%e9%a1%8c/#post-13637706](url)

**Comment by genepine** [comment]
投稿者IDの指定で、WP側投稿が初期状態で投稿者指定できた

**Comment by genepine** [comment]
> #8 WP側投稿が初期状態で無名 と
> #2 kintone で公開処理した際、WP上では承認なしで公開したい
> #7 が画像増殖と関連がある気がするので着手します

関連性はなかった

**Comment by Gucchiy** [comment]
すみませんー、一応、解決された事項も neo の皆様にもご説明頂いてから close することに致しましょう！ Project 上は Done で良いかと思います

**Comment by Gucchiy** [comment]
投稿者の名前が「NEO投稿」になる件を Wiki に文書化したのちクローズとします。

**Comment by Gucchiy** [comment]
Wiki に記載しました！
https://github.com/Gucchiy/neo/wiki

**Comment by Gucchiy** [comment]
スプリント2 クローズ確認。
