### ISSUE TITLE
複数の投稿者をKintoneで選びWordPress側にも反映したい

### ISSUE THREAD

**Issue by genepine** [Gucchiy/neo#9]
三浦さん
>「投稿した人」が現状同一人物のような印象ですが、個人までは特定せずとも投稿元をkintoneで選択できれば・・・と感じました。

**Comment by genepine** [comment]
松野
>管理者が承認してWordPress側でも投稿した人が一人です。
これは日記をNEOさん名義のみで書くのか、NEOの誰々さんが書きました、などと署名を入れるのか決める必要があります。
また投稿者の複数選択はWordPress側の機能の追加が必要です。

**Comment by genepine** [comment]
WP側投稿が初期状態で無名 のコードと連携しないとおそらくできない
[https://github.com/Gucchiy/neo/issues/8](url)

**Comment by Gucchiy** [comment]
運用上、本文に署名を入れていただくことで対応。
エントリー上の名前（nkwpadm）は表示されないようにする。そののちクローズ

**Comment by genepine** [comment]
エントリー上の名前（nkwpadm）は表示されないようにした
Katawara デザイン設定 
投稿詳細ページで投稿者名を表示しない　にチェック
（WordPressテーマがKatarawa, Lightningの場合)
[wordpress 投稿者 非表示](https://bit.ly/2H0UvRj)

**Comment by Gucchiy** [comment]
すみません～、こちらも一旦、Neo の皆様にもご説明頂いた上で Close と致しましょう！Project 上は Done で良いかと思います！

**Comment by Gucchiy** [comment]
11/18 付け打ち合わせにてクローズ承認
